name: Run Python Script and Commit Output

on:
  schedule:
    # Run the workflow every 6 hours
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Set up Python
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    # Install Chrome and ChromeDriver
    - name: Install Chrome and ChromeDriver
      uses: nanasess/setup-chromedriver@v2


    # Install dependencies
    - name: Install dependencies
      run: |
        pip install requests pandas selenium webdriver-manager

    # Run the Python script
    - name: Run Python Script
      run: |
        python main.py

    # Commit and push changes
    - name: Commit and Push Changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add .
        if git diff-index --quiet HEAD; then
          echo "No changes to commit"
          exit 0
        fi
        git commit -m "Updated data on $(date +'%Y-%m-%d %H:%M:%S')"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}